version: '3'

services:
  guestblog:
    image: ${COMPOSE_IMAGE_NAME}
    container_name: ${COMPOSE_PROJECT_NAME}-${GUESTBLOG_CONTAINER_NAME}
    build: .
    ports:
      - "80:8080" # tomcat port

#  mongodb:
#    image: mongo:latest
#    container_name: ${COMPOSE_PROJECT_NAME}-${MONGO_CONTAINER_NAME}
#    network_mode: "service:guestblog"