server:
  error:
    whitelabel:
      enabled: false
  port: 80
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 50MB


