server:
  error:
    whitelabel:
      enabled: false
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 50MB
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost/test}
logging:
  level:
    root: info
security:
  admin:
    secret: ${ADMIN_SECRET:admin}
  jwt:
    secret: ${JWT_SECRET:verySecretJwtSecret}
    expiration: 28800
