server:
  error:
    disable-default-exception-handling: true
    whitelabel:
      enabled: false
  port: ${GB_SERVER_PORT:8080}
spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH2_GOOGLE_CLIENT_ID}
            clientSecret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
          facebook:
            clientId: ${OAUTH2_FACEBOOK_CLIENT_ID}
            clientSecret: ${OAUTH2_FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile
  sql:
    init:
      schema-locations:
        - classpath:schema.sql
      data-locations:
        - classpath:data.sql
      mode: always
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 50MB
  jackson:
    default-property-inclusion: non_null

  # There is problem with verification of postgres's CLOB by Hibernate. You can
  # to find more information here:
  # https://vkuzel.com/spring-boot-jpa-hibernate-atomikos-postgresql-exception
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      leak-detection-threshold: 60000
      maximum-pool-size: 100
    url: ${GB_POSTGRES_URL:jdbc:postgresql://localhost:5432/testdb}
    username: ${GB_POSTGRES_USERNAME:postgres}
    password: ${GB_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
# Springdoc
springdoc:
  packages-to-scan: com.stikipixels.backend
