version: '3.9'

networks:
  gb-internal:

volumes:
  db-volume:
  db-tblspc:
  elastic-volume:

services:

  guestblog:
    container_name: ${COMPOSE_PROJECT_NAME}-guestblog
    image: ${COMPOSE_IMAGE_NAME}
    user: ${CURRENT_UID}
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "80:8080" # tomcat port
    environment:
      - OTEL_SERVICE_NAME=guestblog
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_INSTRUMENTATION_JDBC_DATASOURCE_ENABLED=true
      - OTEL_INSTRUMENTATION_SPRING_BOOT_ACTUATOR_AUTOCONFIGURE_ENABLED=true
      - GB_POSTGRES_URL=jdbc:postgresql://postgresql:5432/gbdb
    depends_on:
      postgresql:
        condition: service_healthy
      hazelcast:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - gb-internal

  postgresql:
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    image: postgres
    build:
      context: postgres/
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 2s
      timeout: 3s
      retries: 3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
      - db-tblspc:/u01
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432" # postgresql port
    env_file:
      - .env
    networks:
      - gb-internal

  elastic:
    container_name: ${COMPOSE_PROJECT_NAME}-elastic
    image: elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx512m"
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
    volumes:
      - elastic-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://elastic:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - .env
    networks:
      - gb-internal

  hazelcast:
    container_name: ${COMPOSE_PROJECT_NAME}-hazelcast
    image: hazelcast/hazelcast
    environment:
      - JAVA_OPTS=-Xms512M -Xmx1024M
      - HZ_CLUSTERNAME=gb-hazelcast
    ports:
      - "5701:5701"
    healthcheck:
      test: curl -f http://hazelcast:5701/hazelcast/health/node-state || exit 1
      interval: 2s
      timeout: 3s
      retries: 3
    env_file:
      - .env
    networks:
      - gb-internal

  zipkin:
    container_name: ${COMPOSE_PROJECT_NAME}-zipkin
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elastic:9200
      - ES_INDEX=zipkin
      - ES_USERNAME=elastic
      - ES_PASSWORD=elastic
    ports:
      - "9411:9411"
    depends_on:
      elastic:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - gb-internal
