include:
  - docker-compose.env.yml

services:

  guestblog:
    image: guestblog
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080" # tomcat port
    environment:
      - OTEL_SERVICE_NAME=guestblog
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
      - OTEL_TRACES_EXPORTER=zipkin
      - OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - OTEL_INSTRUMENTATION_JDBC_DATASOURCE_ENABLED=true
      - OTEL_INSTRUMENTATION_SPRING_BOOT_ACTUATOR_AUTOCONFIGURE_ENABLED=true
      - GB_POSTGRES_URL=jdbc:postgresql://postgresql:5432/gbdb
    depends_on:
      flyway:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
      zipkin:
        condition: service_healthy
    networks:
      - gb-internal
