networks:
  gb-internal:

volumes:
  db-volume:
  db-tblspc:
  kafka-volume:
  opensearch-volume:

services:

  postgresql:
    image: postgres
    build:
      context: postgres/
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
      - db-tblspc:/u01
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    networks:
      - gb-internal

  flyway:
    image: redgate/flyway
    command: migrate info
    volumes:
      - ./flyway/flyway.toml:/flyway/conf/flyway.toml:ro
      - ../db/changelog/:/flyway/sql:ro
    networks:
      - gb-internal
    depends_on:
      postgresql:
        condition: service_healthy

  kafka:
    image: confluentinc/cp-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Setup in KRaft
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Cluster
      - CLUSTER_ID=AAAAAAAAAAAAAAAAAAAAAA
    volumes:
      - kafka-volume:/var/lib/kafka/data
    ports:
      - "29092:29092"
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - gb-internal

  opensearch:
    image: opensearchproject/opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms128m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpenSearch#0
      - plugins.security.ssl.transport.enforce_hostname_verification=false
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.transport.pemtrustedcas_filepath=root-ca.pem
      - plugins.security.ssl.http.pemtrustedcas_filepath=root-ca.pem
      - plugins.security.audit.type=internal_opensearch
      - plugins.security.enable_snapshot_restore_privilege=true
      - plugins.security.check_snapshot_restore_write_privileges=true
      - plugins.security.restapi.roles_enabled=[ "all_access", "security_rest_api_access" ]
      - cluster.routing.allocation.disk.threshold_enabled=false
      - opendistro_security.audit.config.disabled_rest_categories=NONE
      - opendistro_security.audit.config.disabled_transport_categories=NONE
      - plugins.security.ssl.transport.pemcert_filepath=node.pem
      - plugins.security.ssl.transport.pemkey_filepath=node-key.pem
      - plugins.security.ssl.http.pemcert_filepath=node.pem
      - plugins.security.ssl.http.pemkey_filepath=node-key.pem
    volumes:
      - ./certs/root-ca.crt:/usr/share/opensearch/config/root-ca.pem:ro
      - ./certs/admin.crt:/usr/share/opensearch/config/admin.pem:ro
      - ./certs/admin.key:/usr/share/opensearch/config/admin-key.pem:ro
      - ./certs/node.crt:/usr/share/opensearch/config/node.pem:ro
      - ./certs/node.key:/usr/share/opensearch/config/node-key.pem:ro
      - opensearch-volume:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: curl -k -s --fail -u admin:OpenSearch#0 https://localhost:9200/_cluster/health || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - gb-internal

  data-prepper:
    restart: unless-stopped
    image: opensearchproject/data-prepper
    volumes:
      - ./data-prepper/trace_analytics_no_ssl_2x.yml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./data-prepper/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
      - ./certs/root-ca.crt:/usr/share/data-prepper/root-ca.crt
    ports:
      - "21890:21890"
    networks:
      - gb-internal
    depends_on:
      opensearch:
        condition: service_healthy
