include:
  - docker-compose.env.yml

services:

  guestblog:
    image: guestblog
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080" # tomcat port
    environment:
      - OTEL_JAVAAGENT_CONFIGURATION_FILE=/etc/otel-collector-config.yml
      - GB_POSTGRES_URL=jdbc:postgresql://postgresql:5432/gbdb
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
    depends_on:
      flyway:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
      data-prepper:
        condition: service_started
    networks:
      - gb-internal

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - gb-internal
    depends_on:
      opensearch:
        condition: service_healthy
