networks:
  internal-network:

volumes:
  postgres-volume:
  kafka-volume:
  opensearch-volume:

services:
  postgresql:
    image: docker.io/postgres
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gbdb
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - internal-network

  flyway:
    image: docker.io/redgate/flyway
    command: migrate info
    volumes:
      - ../db/changelog/:/flyway/sql:ro
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgresql:5432/gbdb
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=postgres
    networks:
      - internal-network
    depends_on:
      postgresql:
        condition: service_healthy

  cassandra:
    image: docker.io/cassandra:4.1.1
    environment:
      - "MAX_HEAP_SIZE=1G"
      - "HEAP_NEWSIZE=256M"
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra", '-e "describe keyspaces"']
      start_period: 5s
      interval: 3s
      timeout: 5s
      retries: 30
    ports:
      - "9042:9042"
    expose:
      - "9042"
    networks:
      - internal-network

  kafka:
    image: docker.io/confluentinc/cp-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      # Setup in KRaft
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Cluster
      - CLUSTER_ID=AAAAAAAAAAAAAAAAAAAAAA
    volumes:
      - kafka-volume:/var/lib/kafka/data
    ports:
      - "29092:29092"
    expose:
      - "29092"
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 5s
      interval: 3s
      timeout: 5s
      retries: 10
    networks:
      - internal-network

  opensearch:
    image: docker.io/opensearchproject/opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms128m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=OpenSearch#0
      - plugins.security.ssl.http.enabled=false
    volumes:
      - opensearch-volume:/usr/share/opensearch/data
    expose:
      - "9200"
      - "9600"
    healthcheck:
      test: curl -k -s --fail -u admin:OpenSearch#0 http://localhost:9200/_cluster/health || exit 1
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal-network

  cadence:
    image: docker.io/ubercadence/server:master-auto-setup
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
      - "7833:7833"
      - "7936:7936"
    environment:
      - CASSANDRA_SEEDS=cassandra
      - KAFKA_SEEDS=kafka
      - ENABLE_ES=true
      - ES_SEEDS=opensearch
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - FRONTEND_PPROF_PORT=7936
      - LOG_LEVEL=debug
    networks:
      - internal-network
    depends_on:
      cassandra:
        condition: service_healthy
      kafka:
        condition: service_healthy
      opensearch:
        condition: service_healthy

  data-prepper:
    restart: unless-stopped
    image: docker.io/opensearchproject/data-prepper
    volumes:
      - ./data-prepper/trace_analytics_no_ssl_2x.yml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./data-prepper/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    ports:
      - "21890:218905601" # Traces
      - "21891:21891" # Metrics
      - "21892:21892" # Logs
    networks:
      - internal-network
    depends_on:
      opensearch:
        condition: service_healthy

  ##############
  # UI section
  ##############

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8081:8080"
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    networks:
      - internal-network
    depends_on:
      kafka:
        condition: service_healthy

  opensearch-dashboard:
    image: docker.io/opensearchproject/opensearch-dashboards
    ports:
      - "8082:5601" # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - internal-network
    depends_on:
      opensearch:
        condition: service_healthy

  cadence-web:
    image: docker.io/ubercadence/web
    environment:
      - "CADENCE_GRPC_PEERS=cadence:7833"
    ports:
      - "8083:8088"
    networks:
      - internal-network
    depends_on:
      cadence:
        condition: service_started
