otel-logs-pipeline:
  delay: "100"
  source:
    otel_logs_source:
      port: 21892
      ssl: false
      authentication:
        unauthenticated:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        username: "admin"
        password: "OpenSearch#0"
        bulk_size: 10
        index_type: custom
        index: otel-v1-logs-%{yyyy.MM.dd}
        number_of_replicas: 0

otel-metrics-pipeline:
  delay: "100"
  source:
    otel_metrics_source:
      port: 21891
      ssl: false
      authentication:
        unauthenticated:
#  processor:
#    - otel_metrics_raw_processor:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        username: "admin"
        password: "OpenSearch#0"
        bulk_size: 10
        index_type: custom
        index: otel-v1-metrics-%{yyyy.MM.dd}
        number_of_replicas: 0

entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      port: 21890
      ssl: false
      authentication:
        unauthenticated:
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"

raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        username: "admin"
        password: "OpenSearch#0"
        index_type: trace-analytics-raw

service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        username: "admin"
        password: "OpenSearch#0"
        index_type: trace-analytics-service-map
