entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline"
    - pipeline:
        name: "service-map-pipeline"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
    - otel_trace_group:
        hosts: [ "http://opensearch:9200" ]
        username: "admin"
        password: "OpenSearch#0"
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        username: "admin"
        password: "OpenSearch#0"
        index_type: trace-analytics-raw
service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        username: "admin"
        password: "OpenSearch#0"
        index_type: trace-analytics-service-map
